# Unique name for this workflow
name: On pull request to develop - Check deployment against Prod

# Definition when the workflow should run
on:
    push:
        branches:
            - master

# Jobs to be executed
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:

            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            - name: 'Build and Deploy'
              uses: tiagonnascimento/sfdx-orgdev-build-deploy@v1.1
              with:
                type: 'production'
                certificate_path: certificates/server.key
                client_id: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
                username: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
                checkonly: true
                manifest_path: manifest/package.xml
