name: Org Deployment CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Authorizing Org
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile certificates/server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultusername
    - name: Deploying Metadata
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: force:source:convert --rootdir=force-app --outputdir=convert
    - name: Deploying Metadata
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: force:source:deploy --manifest manifest/package.xml
